module.exports = {
  types: [
    { value: 'feat', name: 'feat:     new feature' },
    { value: 'fix', name: 'fix:      bug fix' },
    { value: 'chore', name: 'chore:    maintenance task' },
    { value: 'docs', name: 'docs:     documentation changes' },
    { value: 'refactor', name: 'refactor: internal change without altering expected behavior' },
    { value: 'perf', name: 'perf:     performance improvement' },
    { value: 'test', name: 'test:     test changes' },
    { value: 'ci', name: 'ci:       CI or pipeline changes' },
    { value: 'build', name: 'build:    build or dependency changes' },
    { value: 'style', name: 'style:    formatting changes with no logic impact' },
    { value: 'revert', name: 'revert:   revert a previous commit' },
  ],
  scopes: [
    'app',
    'setup',
    'router',
    'auth',
    'maps',
    'wallet',
    'social',
    'observability',
    'testing',
    'docs',
    'deps',
    'git',
    'ci',
    'ui',
    'types',
  ],
  allowCustomScopes: true,
  allowEmptyScopes: true,
  customScopesAlign: 'bottom',
  customScopesAlias: 'custom scope',
  emptyScopesAlias: 'no scope',
  messages: {
    type: 'Select the type of change you are committing:',
    scope: 'Select the scope for this change:',
    customScope: 'Enter the custom scope:',
    subject: 'Write a short imperative description:\n',
    body: 'Add optional context. Use "|" for line breaks:\n',
    breaking: 'Describe the breaking change:\n',
    footer: 'Reference closed issues, for example #12:\n',
    confirmCommit: 'Do you want to create this commit?',
  },
};
