module.exports = {
  types: [
    { value: 'feat', name: 'feat:     nueva funcionalidad' },
    { value: 'fix', name: 'fix:      correccion de bug' },
    { value: 'chore', name: 'chore:    tarea de mantenimiento' },
    { value: 'docs', name: 'docs:     cambios de documentacion' },
    { value: 'refactor', name: 'refactor: cambio interno sin alterar comportamiento esperado' },
    { value: 'perf', name: 'perf:     mejora de rendimiento' },
    { value: 'test', name: 'test:     cambios en pruebas' },
    { value: 'ci', name: 'ci:       cambios en integracion o pipelines' },
    { value: 'build', name: 'build:    cambios de build o dependencias' },
    { value: 'style', name: 'style:    cambios de formato sin impacto logico' },
    { value: 'revert', name: 'revert:   revierte un commit anterior' },
  ],
  scopes: [
    'app',
    'setup',
    'router',
    'auth',
    'maps',
    'wallet',
    'social',
    'observability',
    'testing',
    'docs',
    'deps',
    'git',
    'ci',
    'ui',
    'types',
  ],
  allowCustomScopes: true,
  allowEmptyScopes: true,
  customScopesAlign: 'bottom',
  customScopesAlias: 'scope personalizado',
  emptyScopesAlias: 'sin scope',
  messages: {
    type: 'Selecciona el tipo de cambio que vas a commitear:',
    scope: 'Selecciona el scope de este cambio:',
    customScope: 'Escribe el scope personalizado:',
    subject: 'Escribe una descripcion corta e imperativa:\n',
    body: 'Añade contexto adicional opcional. Usa "|" para salto de linea:\n',
    breaking: 'Describe el breaking change:\n',
    footer: 'Referencia issues cerrados, por ejemplo #12:\n',
    confirmCommit: '¿Confirmas este commit?',
  },
};
